{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python388jvsc74a57bd0537ba0ffad682576d6afadc0305e2c3929b126cc8ecab491c1b8e689fbaa6d6a",
   "display_name": "Python 3.8.8 64-bit ('mosaic': conda)"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "import os\n",
    "os.environ[\"TERRA_CONFIG_PATH\"] = \"/Users/sabrieyuboglu/code/spr-21/terra_config.json\"\n",
    "\n",
    "from spr.nb import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import mosaic as ms\n",
    "from mosaic.provenance import capture_provenance, ProvenanceObjNode, ProvenanceOpNode, provenance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'DataPanel' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'DataPanel' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'DataPanel' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'DataPanel' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'DataPanel' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'DataPanel' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'DataPanel' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 47, in node\n",
      "    return self._node\n",
      "AttributeError: 'ListColumn' object has no attribute '_node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n",
      "Exception ignored in: <function ProvenanceMixin.__del__ at 0x7f9aae6a6820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/provenance.py\", line 55, in __del__\n",
      "    self.node.cache_repr()\n",
      "  File \"/Users/sabrieyuboglu/code/mosaic/mosaic/columns/numpy_column.py\", line 89, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: 'NumpyArrayColumn' object has no attribute 'node'\n"
     ]
    }
   ],
   "source": [
    "with provenance(enabled=True):\n",
    "    dp1 = DataPanel.from_batch({\n",
    "        \"x\": np.arange(4),\n",
    "        \"y\": np.zeros(4)\n",
    "    })\n",
    "\n",
    "\n",
    "    dp2 = dp1.map(lambda x: {\n",
    "        \"z\": 0,\n",
    "        \"w\": 2\n",
    "    })\n",
    "\n",
    "    dp3 = ms.concat([dp1, dp2], axis=\"columns\")\n",
    "\n",
    "    dp4 = dp3.filter(lambda x: x[\"x\"] > 1)\n",
    "    dp5 = DataPanel.from_batch({\n",
    "        \"x\": np.arange(4),\n",
    "        \"k\": np.zeros(4)\n",
    "    })\n",
    "    dp6 = ms.merge(dp5, dp4, on=\"x\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Test:\n",
    "    attr = \"blah\"\n",
    "    def __init__(self):\n",
    "        pass\n",
    "    \n",
    "    @capture_provenance(capture_args=[\"self\", \"test_arg\"])\n",
    "    def fn(self, dp, test_arg=1):\n",
    "        return  [dp.map(lambda x: {\n",
    "            \"z\": 0,\n",
    "            \"w\": 2\n",
    "        }), dp.map(lambda x: {\n",
    "            \"z\": 0,\n",
    "            \"w\": 2\n",
    "        })]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [],
   "source": [
    "with provenance(enabled=True):\n",
    "    dp1 = DataPanel.from_batch({\n",
    "        \"x\": np.arange(4),\n",
    "        \"y\": np.zeros(4),\n",
    "        \"y_hat\": np.ones(4)\n",
    "    })\n",
    "\n",
    "    test = Test()\n",
    "    out1, out2 = test.fn(dp1)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "'blah'"
      ]
     },
     "metadata": {},
     "execution_count": 41
    }
   ],
   "source": [
    "out2.node.last_parent[0].meta[\"self\"].attr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [],
   "source": [
    "del dp3"
   ]
  },
  {
   "source": [
    "1. Caller \n",
    " "
   ],
   "cell_type": "markdown",
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "output_type": "display_data",
     "data": {
      "text/plain": "Cytoscape(data={'elements': {'nodes': [{'data': {'id': 140660859609040, 'name': 'DataPanel(num_rows: 4)', 'typ…",
      "application/vnd.jupyter.widget-view+json": {
       "version_major": 2,
       "version_minor": 0,
       "model_id": "08b20eb310514ee4824476faed03d163"
      }
     },
     "metadata": {}
    }
   ],
   "source": [
    "from mosaic.provenance import visualize_provenance\n",
    "\n",
    "visualize_provenance(dp6, show_columns=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "dp1 = DataPanel.from_batch({\n",
    "    \"x\": np.arange(4),\n",
    "    \"y\": np.zeros(4)\n",
    "})\n",
    "\n",
    "dp2 = dp1.map(lambda x: {\n",
    "    \"z\": 0,\n",
    "    \"w\": 2\n",
    "})\n",
    "\n",
    "dp3 = ms.concat([dp1, dp2], axis=\"columns\")\n",
    "\n",
    "dp4 = dp3.filter(lambda x: x[\"x\"] > 1)\n",
    "dp5 = DataPanel.from_batch({\n",
    "    \"x\": np.arange(4),\n",
    "    \"k\": np.zeros(4)\n",
    "})\n",
    "dp6 = ms.merge(dp5, dp4, on=\"x\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "[]"
      ]
     },
     "metadata": {},
     "execution_count": 15
    }
   ],
   "source": [
    "dp6.node.parents"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "output_type": "display_data",
     "data": {
      "text/plain": "Cytoscape(data={'elements': {'nodes': [], 'edges': []}}, layout_name='breadthfirst', visual_style=[{'selector'…",
      "application/vnd.jupyter.widget-view+json": {
       "version_major": 2,
       "version_minor": 0,
       "model_id": "10bc9b3cd2c140209fc0737752654c42"
      }
     },
     "metadata": {}
    }
   ],
   "source": [
    "from mosaic.provenance import visualize_provenance\n",
    "\n",
    "visualize_provenance(dp6, show_columns=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ]
}